name: go_green
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #geolocator:
  geolocator: ^7.3.0

  #svg_image
  flutter_svg: ^0.22.0

  #Flutter Fire
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  firebase_database: ^7.1.1

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2


  font_awesome_flutter: ^9.1.0
  carousel_slider: ^4.0.0

  pinput: ^1.2.0

  #spinkit package
  flutter_spinkit: ^5.0.0

  #http package
  http: ^0.13.3

  #Email Validator
  email_validator: ^2.0.1

  #Checks Internet Connectivity
  connectivity_plus: ^1.0.5

  #Provider
  provider: ^5.0.0

  #Cache Image
  cached_network_image: ^3.0.0

  #rating
  flutter_rating_bar: ^4.0.0

  #url_launcher
  url_launcher: ^6.0.9

  #toast
  fluttertoast: ^8.0.7

  #razorpay
  razorpay_flutter: ^1.2.7

  #transparent image
  transparent_image: ^2.0.0

  #image zoom
  photo_view: ^0.12.0

  #geocode
  geocoding: ^2.0.0

  #audioplayers:
  audioplayers: ^0.19.1

  #share plugin
  share_plus: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo2.png"


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/category/
    - images/categoryLayout/
    - images/svg/
    - assets/
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
          weight: 900
        - asset: fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Lato-Regular.ttf
          weight: 400
        - asset: fonts/Lato-Thin.ttf
          weight: 100
        - asset: fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic



flutter_native_splash:
  color: "#65bc6a"
  image: images/logo2.png

